//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int Roomnumber { get; set; }
        public int BedCount { get; set; }
        public int Bookings { get; set; }
        public Nullable<int> Issues { get; set; }
        public System.DateTime LastCleaned { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
        public virtual Issue Issue { get; set; }
        public virtual Standard Standard { get; set; }
        public virtual Suite Suite { get; set; }
        public virtual Superior Superior { get; set; }
    }
}
