//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public int rNumber { get; set; }
        public int ROOM_SZ { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
