<?xml version="1.0" encoding="utf-8"?><Database Name="Dat154Project" Class="CreatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dat154.database.windows.net;Initial Catalog=Dat154Project;User ID=dat154vaar18;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="sqltest.Properties.Settings" SettingsPropertyName="Dat154ProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bookings" Member="Bookings">
    <Type Name="Booking">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="CheckedIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CheckedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerUID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Orders" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Booking_Room" Member="Rooms" ThisKey="Id" OtherKey="bookingsId" Type="Room" />
      <Association Name="Customer_Booking" Member="Customer" ThisKey="CustomerUID" OtherKey="Id" Type="Customer" IsForeignKey="true" />
      <Association Name="Order_Booking" Member="Order" ThisKey="Orders" OtherKey="itemId" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="lName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="balance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Booking" Member="Bookings" ThisKey="Id" OtherKey="CustomerUID" Type="Booking" />
    </Type>
  </Table>
  <Table Name="dbo.Issues" Member="Issues">
    <Type Name="Issue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Completed" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Issue_Room" Member="Rooms" ThisKey="Id" OtherKey="issues" Type="Room" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="itemName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="total" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="ordered" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Order_Booking" Member="Bookings" ThisKey="itemId" OtherKey="Orders" Type="Booking" />
      <Association Name="OrderSpec_Order" Member="OrderSpec" ThisKey="itemId" OtherKey="ItemId" Type="OrderSpec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderSpecs" Member="OrderSpecs">
    <Type Name="OrderSpec">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="OrderSpec_Order" Member="Order" ThisKey="ItemId" OtherKey="itemId" Type="Order" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="number" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="beds" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bookingsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="issues" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Booking_Room" Member="Booking" ThisKey="bookingsId" OtherKey="Id" Type="Booking" IsForeignKey="true" />
      <Association Name="Issue_Room" Member="Issue" ThisKey="issues" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
</Database>